### ISSUE TITLE
invalid prop style error

### ISSUE THREAD

**Issue by dylanvu** [UCI-Capstone-Paciolan-2024/PacTrivia#10]
investigate and resolve this invalid prop style error

![Image](https://github.com/UCI-Capstone-Paciolan-2024/PacTrivia/assets/75911565/38b89b8b-8837-4f2d-a1a4-857afd05b3fb)

**Comment by duonghv1** [comment]
turns out this warning comes from an opened issue from the package 'react-native-circular-progress' itself. A quick fix has been provided by one of the user and is also already added to the readme.md for anyone who wants to fix it locally. 

Since the fix has to do with modifying a src file inside the node-modules/react-native-circular-progress, I am not committing anything.
